name: Rust CI

on:
  push:
    branches:
    - "main"
    - "renovate/**"
  pull_request:

permissions:
  contents: write
  checks: write

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

    - name: Format Code
      run: cargo fmt --all -- --check

  clippy:
    name: Check Clippy
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

    - name: Run Clippy
      run: cargo clippy --all -- -D warnings

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [fmt, clippy]

    steps:
    - name: Check out
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4360b52568e2003a75bf9bc1d59f33a8e3fc893c # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2

    - name: Main Tests
      run: cargo nextest run --workspace --profile ci

    - name: Doc Tests
      run: cargo test --doc

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - uses: andrewaylett/pre-commit-action@afeae3a6d8a9e89c054107c2da12c0dc832239a4 # v4
      with:
        extra_args: --all-files --hook-stage pre-merge-commit
