name: Rust CI

on:
  push:
    branches:
    - "main"
    - "renovate/**"
  pull_request:

permissions:
  contents: write
  checks: write

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Format Code
      run: cargo fmt --all -- --check

  clippy:
    name: Check Clippy
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Run Clippy
      run: cargo clippy --all -- -D warnings

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: [fmt, clippy]

    steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up Rust (stable)
      uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable

    - name: Cache build artifacts
      uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

    - name: Main Tests
      run: cargo nextest run --workspace --profile ci

    - name: Doc Tests
      run: cargo test --doc

  pre-commit:
    name: Pre-Commit
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - uses: andrewaylett/pre-commit-action@1d9883e9e6a8b9525d5ac8cbbf2952ba2cb9452a # v4
      with:
        extra_args: --all-files --hook-stage pre-merge-commit
